### ISSUE TITLE
USER STORY:  Orders and Checkout - Order confirmation

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#11]
As a **site user** I can **get email confirmation about my order** so that **I have all the details of my order**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- Users can view their order details after they completed the order
- Users need to receive an email with the order confirmation

**Task**

- [ ]  Wire it up with views and URL and the template
- [ ]  Write confirmation email template
- [ ] Email is sent when the order is completed
