### ISSUE TITLE
USER STORY:  Orders and Checkout - Shopping bag items

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#12]
As a **user** I can **see the number of items in shopping bag** so that **I can keep track of what I am purchasing**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- Users can see the number of each product in the bag
- Users can update the number of products from the bag

**Task**

- [ ]  Add  layout for bigger and smaller devices
- [ ] Add  a + / - button enabling the user to control the amount products they are purchasing
- [ ]  Wire it up with views and URL and the template
