### ISSUE TITLE
USER STORY:  Orders and Checkout - Delivery info

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#15]
As a **site user** I can **enter my delivery and shipping info** so that **I can checkout quickly and easily**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- Users can enter the delivery information.
- 
**Task**

- [ ]  create a model, form, and views to set up the logic
- [ ]  Add it to the template
- [ ] User does not need to signup to purchase an item
