### ISSUE TITLE
USER STORY:  Orders and Checkout - Delete Shopping bag items

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#16]
As a **site user** I can **get a notification if i want to delete items from bag** so that **I can rectify my mistake if I pressed the delete button unintentionally**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- Users can delete shopping bag items

**Task**

- [ ]  Notify users if they really want to delete the product
- [ ]  On final confirmation delete the product
- [ ]  Wire it up with views and URL and the template
