### ISSUE TITLE
USER STORY: Admin store management - Add products

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#18]
As a **admin** I can **add products from the site** so that **I do not have to log in to the admin site**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- Store owners can add products

**Task**

- [ ]  Add toast to notify about successful/unsuccessful attempts to add products
- [ ]  Store owners can add products without needing to login into the admin site
- [ ]  Wire it up with views and URL and the template to process this task
