### ISSUE TITLE
USER STORY: Admin store management - Edit Item

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#19]
As a **admin** I can **edit an item** so that **I can edit and update the items easily**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- Store owners can edit products

**Task**
 
- [ ] Instantiate products detail when editing products
- [ ]  Add toast to notify about successful/unsuccessful attempts to edit products
- [ ]  Store owners can eidt products without needing to login into the admin site
- [ ]  Wire it up with views and URL and the template to process this task
