### ISSUE TITLE
USER STORY: Admin store management - Delete item

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#20]
As a **admin** I can **delete item** so that **I can move it from website.**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- Store owners can delete products

**Task**
 
- [ ]  Add toast to notify about successful/unsuccessful attempts to delete products
- [ ]  Store owners can delete products without needing to login into the admin site
- [ ]  Wire it up with views and URL and the template to process this task
