### ISSUE TITLE
USER STORY: Admin store management - Add Faqs

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#21]
As a **Admin** I can **add faqs** so that **I can faqs easily to the page**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- Store owners can add faqs

**Task**
 
- [ ]  Add toast to notify about successful/unsuccessful attempts to add faqs
- [ ]  Store owners can add faqs without needing to login into the admin site
- [ ]  Wire it up with views and URL and the template to process this task
