### ISSUE TITLE
USER STORY: Admin store management - Edit faqs

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#22]
As an **admin** I can **edit faqs** so that **I can change them if needed to**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- Store owners can edit faqs

**Task**
 

- [ ] Instantiate faqs detail when editing faqs
- [ ]  Add toast to notify about successful/unsuccessful attempts to edit faqs
- [ ]  Store owners can edit faqs without needing to login into the admin site
- [ ]  Wire it up with views and URL and the template to process this task
