### ISSUE TITLE
USER STORY: Admin store management -  Delete Faqs

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#23]
As an **admin** I can **delete faqs** so that **I can remove from the page**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- Store owners can delete faqs

**Task**
 
- [ ]  Add toast to notify about successful/unsuccessful attempts to delete faqs
- [ ]  Store owners can delete faqs without needing to login into the admin site
- [ ]  Wire it up with views and URL and the template to process this task
