### ISSUE TITLE
USER STORY: Account Registration and Login - receive email confirmation

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#26]
As a **site user** I can **get email confirmation** so that **I know that my email id is correct**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- User needs to receive a confirmation email on registration
- Once the email is confirmed user can log in to the site
- Notify a user about login and account creation

**Task**

- [ ] Use all auth to do all the hard work
- [ ] Write an email template to send emails to the user
- [ ]  Customise all auth templates to match the site
