### ISSUE TITLE
USER STORY: Products - Search

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#4]
As a **site user** I can **search products** so that **I can find them easily**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- User can search for products
- User can click on the searched products to view the products

**Task**

- [ ]  Add a search option on the page
- [ ]  Wire it up with views and url and the template
- [ ]  The search can look up insensitive case(get records that contain a specified value)
