### ISSUE TITLE
USER STORY: Products - Sort out products

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#5]
As a **site user** I can **sort out products** so that **I can view them in different ways**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- User can sort out the products

**Task**

- [ ]  Add a sort out option  on the page
- [ ]  Wire it up with views and the template
- [ ]  It will sort out items into the category the user has clicked on
