### ISSUE TITLE
USER STORY: Products - Quantity

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#7]
As a **site user** I can **change the quantity** so that **I can add the required number of items in the bag**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- User can change the quantity of the products
- The +/- button will disable at 1 and 100,

**Task**

- [ ]  Add + / - button on the product detail page and shopping bag page
- [ ]  Wire it up with views and url and the template
- [ ] Use javascript to to restrict user from selecting values more or less than stated.
