### ISSUE TITLE
USER STORY: Products - Notifications on activity

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#8]
As a **site user** I can **get notified** so that **i know every steps i am taking before buying products**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- Users should know what they are doing by giving them visual interactions

**Task**

- [ ]  Add toast which will pop up when a user does something
- [ ]  the toast must have different colors, eg success, info etc colors
- [ ] Toast must disappear after a few seconds
