### ISSUE TITLE
USER STORY: Quantity adjustment in shopping bag

### ISSUE THREAD

**Issue by shahid129** [shahid129/oliver-dein#9]
As a **site user** I can **adjust shopping bag quantity** so that **I don not have to go back to products to adjust my bag**

**Comment by shahid129** [comment]
**Acceptance Criteria***

- User can change the quantity of the products
- The +/- button will be disable at 1 and 100,

**Task**

- [ ]   Add + / - button on the product detail page and shopping bag page
- [ ]  Wire it up with views and URL and the template
- [ ]  Use javascript to restrict users from selecting values more or less than stated.
